spring:
  main:
    banner-mode: off
  application:
    name: spring-boot-service
  config:
    import: "optional:aws-parameterstore:,optional:aws-secretsmanager:"
  profiles:
    active: localhost
  jackson:
    default-property-inclusion: non_empty
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_BQiFUBlRy
  flyway:
    enabled: false

previewme:
  resource:
    path: /spring-boot-service

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
    enable:
      jvm: true
      http: true
      cache: true
      hikaricp: true
      system: false
      jdbc: false
      logback: false
      tomcat: false
      process:
        enabled: false
        cpu: true
    tags:
      application: ${spring.application.name}
      container: ${HOSTNAME:}${COMPUTERNAME:}

server:
  error:
    whitelabel:
      enabled: false

aws:
  paramstore:
    region: us-east-1
  secretsmanager:
    region: us-east-1


---
spring:
  config:
    activate:
      on-profile: "localhost"

---
spring:
  config:
    activate:
      on-profile: "development"

---
spring:
  config:
    activate:
      on-profile: "production"